### ISSUE TITLE
테스트용 example API & DB 설정

### ISSUE THREAD

**Issue by IMRaccoon** [Konkuk-JJabaries/ExpressJS-Study#1]
- 11번가 활용
- expressJS를 통해서 11번가를 호출하는 기능
- MySQL 를 활용하여 expressJS로 추가, 조회, 삭제, 변경 기능 수행하는 기능 구현

- [x] Express 에서 API 호출
- [x] DB세팅
- [x] DB에 예약어가 있을 경우 DB로 호출

**Comment by s5kywa1k3r** [comment]
추후 실행 명령어 및 사용 모듈 버전 markdown에 추가해주세요.
물론 package.json으로 설정 미리해주면 좋습니다.

**Comment by IMRaccoon** [comment]
설정 했구 README 도 수정했슴니당 알려줘서 고마워유
