### ISSUE TITLE
DB & API를 활용한 제대로 된 TEST 진행

### ISSUE THREAD

**Issue by IMRaccoon** [Konkuk-JJabaries/ExpressJS-Study#4]
- [x] ExpressJS 를 TypeScript로 바꿀 예정(Backend team과 동일한 버전 3.7.4 로 진행할 예정)
- [x] 테스트용 API 하나 더 추가
- [x] DB 바뀌는 내역에 따라 실시간으로 반영해서 API 사용 시에, DB에 임시적으로 저장하는 기능 구현
- [x] DB에서 먼저 검색 한 후에 해당 쿼리문이 없거나 적을 경우 API 호출하는 코드 구현

**Comment by beoms96** [comment]
저도 여기 참여 하겠습니다 사장님. 저한테 assign 되어있어야 보기 편해서요

**Comment by beoms96** [comment]
네 번째 기능 아직 완벽하진 않지만 데이터베이스에 query 날리는 작업까지는 완료했습니다.

**Comment by beoms96** [comment]
세번째 요구사항이 잘 이해가 안되는데 설명해주시면 감사하겠습니다.

**Comment by IMRaccoon** [comment]
세번째 요구사항은 cache처럼 사용하는 예전 아이디어라 끝난 내용입니당 닫을게여
