### ISSUE TITLE
DataBase 구조 생각하기

### ISSUE THREAD

**Issue by IMRaccoon** [Konkuk-JJabaries/ExpressJS-Study#5]
- [x] DataBase 구조 생각하기
- [x] 필요한 쿼리문 짜기

브랜치 따로 파서 README 같은 걸로 Query문 우리가 사용할 만한거 
작성해서 설명 덧붙여가지고 pull request 날려주세용

**Comment by beoms96** [comment]
테이블 구조랑 애트리뷰트 형식 나오면 그 때 팔게유!!

**Comment by IMRaccoon** [comment]
드렸습니당 확인하고 계속 갱신해주세여

**Comment by beoms96** [comment]
일단 테이블 형식

create table ProductList (
    id varchar(24) not null,
    title varchar(50) not null primary key,
    price int not null,
    image varchar(100),
    origin_url varchar(100) not null,
    sitecode varchar(10) not null,
    category varchar(15),
    date date,
    seller varchar(30),
    status varchar(10)
);

**Comment by beoms96** [comment]
24시간 주기로 업데이트할 때 필요한 Database 형식들이고 이 형식 대로 가져와서 저장할 생각입니다. 제일 먼저 데이터를 가져오는 사이트부터 차례대로 접속해서 나중에 사이트별로도 확인할 수 있게 할겁니다.
사용자가 상품명 검색하면 상품명이 포함된 title을 찾아서 데이터 정보들 전부 가져올 생각입니다.

**Comment by beoms96** [comment]
나중에 카테고리별로 인덱싱 연결할 생각도 있습니다.

**Comment by beoms96** [comment]
사용자가 상품명 검색 시 상품명이 포함된 name의 정보를 DB에서 찾아 데이터가 20개 이상이라면 DB의 정보 출력, 미만이라면 api 정보 출력하는 것까지 구현했습니다.
