### ISSUE TITLE
ExpressJS-Study npm run build 에러 발생

### ISSUE THREAD

**Issue by s5kywa1k3r** [Konkuk-JJabaries/ExpressJS-Study#7]
docker에서 ExpressJS-Study 폴더에서 npm run build 실행 시 Error가 발생하는데 정상인가요?
각 명령어를 실행할 경우
- npm install 시 warning이 출력됩니다.
- npm run build시 error가 발생합니다.

![Screenshot from 2020-01-07 00-36-58](https://user-images.githubusercontent.com/11014035/71828675-20da2500-30e6-11ea-904f-024ed31ca221.png)

**Comment by beoms96** [comment]
관리자모드로 한번 해보실 수 있나요??

**Comment by s5kywa1k3r** [comment]
왼쪽 위에 계정을 보시면 아시겠지만 root 계정에서 실행한 것이라 관리자 계정으로 실행한 것입니다.

**Comment by s5kywa1k3r** [comment]
아 경로가 잘못되었었습니다. 하지만 다른 경로에서도 error가 발생하는데 그 issue는 다시 올리도록 하겠습니다.
