### ISSUE TITLE
ExpressJS-Study npm run build 에러 발생

### ISSUE THREAD

**Issue by s5kywa1k3r** [Konkuk-JJabaries/ExpressJS-Study#8]
ExpressJS-Study/express-test 에서 
![Screenshot from 2020-01-07 13-29-01](https://user-images.githubusercontent.com/11014035/71868507-ba8aec00-3151-11ea-8617-fe8e22084400.png)

script가 없다고 에러가 발생합니다.
아무래도 npm run build에서 에러가 발생하는 것으로 추측됩니다.

**Comment by IMRaccoon** [comment]
`npm run build` 는 11st 에서만 사용됩니다.
build를 하는 이유는 Typescript에서 JavaScript로 바꾸기 위함이고
지금 기존의 express-test 레포지토리에서는 JavaScript로 짜여져 있기 때문에 
따로 build할 필요가 없습니다.
11st 폴더에서는 `npm install` 한 뒤에 `npm run build` 그리고 
express-test 폴더에서는 `npm install` 한 뒤에 `npm start`만 걸어주시면 됩니다.

**Comment by s5kywa1k3r** [comment]
네 알겠습니다. 추가적인 사항으로는 docker 실행 시 git clone을 하지 않음으로서 현 README 대로 실행 할 경우 필요한 파일 누락을 확인하였습니다. 이에 현재 시점으로 clone을 완료하였고 container 재부팅으로 해결하였습니다.
